services:
  noise-counter:
    build: .
    ports:
      - "8008:8008"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: "1"
    command: ["flask", "run", "--host=0.0.0.0", "--port=8008", "--debug"]
    volumes:
      - .:/app
